import manifest from "./media-manifest.json";
import { LOCAL_MEDIA } from "./local-media";
import { r2PublicBase, listLive, hasLiveSource } from "./r2";
import {
  buildPublicUrl,
  contentTypeFor,
  type MediaManifest,
  type VenueMediaItem,
} from "./media-types";

/**
 * Where the site's media list comes from, in priority order:
 *
 *   1. a live bucket listing — needs CLOUDFLARE_API_TOKEN or S3 keys
 *   2. the in-memory cache of that listing
 *   3. `lib/media-manifest.json` — a committed snapshot of the bucket
 *   4. `LOCAL_MEDIA` — the bundled `public/` assets
 *
 * Levels 3 and 4 are what make the site work with no credentials at all, and
 * levels 2 + 5 (below) are what stop an unreachable bucket from turning into a
 * request storm or an empty page.
 */
export type MediaSource = "live" | "cache" | "snapshot" | "local";

export type MediaResolution = {
  manifest: MediaManifest;
  source: MediaSource;
  /** True when a live attempt failed and an older copy was served instead. */
  stale: boolean;
  /** Populated only when a live attempt failed. */
  error?: string;
};

/** Re-list at most this often: media changes are rare, requests aren't. */
const SUCCESS_TTL_MS = 60_000;

/**
 * How long to stop trying after a failure. Without this, every page load pays
 * the full 5s listing timeout — an outage becomes an outage *and* a stampede.
 */
const FAILURE_TTL_MS = 30_000;

let cache: { manifest: MediaManifest; at: number } | null = null;
let failure: { at: number; message: string } | null = null;
let inFlight: Promise<MediaManifest> | null = null;

/** Test/verification hook — module state outlives a single request. */
export function resetMediaCache() {
  cache = null;
  failure = null;
  inFlight = null;
}

/**
 * Build a manifest from the committed bucket snapshot.
 *
 * Returns null when there's no public CDN base: snapshot keys are bare object
 * names (`brw (2 of 20).jpg`), so without a base they'd resolve as broken
 * relative URLs instead of falling through to the bundled media.
 */
/**
 * Web-sized copies generated by `npm run media:sync`, keyed by original object.
 *
 * The originals are 2–11 MB and Next aborts any upstream image fetch that takes
 * longer than 7 seconds, so a cold gallery could render broken tiles. Serving
 * the small copy keeps every tile inside that budget while the full-resolution
 * original stays available for the lightbox.
 */
function derivativeFor(key: string) {
  return manifest.objects.find((object) => object.key === key)?.web ?? null;
}

function snapshotManifest(): MediaManifest | null {
  const base = r2PublicBase;
  if (!base || manifest.objects.length === 0) return null;

  const items: VenueMediaItem[] = manifest.objects.map((object) => {
    const web = object.web ?? null;
    return {
      _id: object.key,
      url: buildPublicUrl(base, web ? web.key : object.key),
      // The derivative is re-encoded, so its container decides the type — a
      // `.mov` original is served as an `.mp4` copy, and callers rely on that
      // being reported honestly.
      contentType: web ? contentTypeFor(web.key) : object.contentType,
      // The served size, so section allocation reasons about what the browser
      // actually downloads rather than the weight of the original.
      size: web ? web.size : object.size,
      kind: object.kind === "video" ? "video" : "image",
    } as VenueMediaItem;
  });

  const images = items.filter((item) => item.kind === "image");
  const videos = items.filter((item) => item.kind === "video");
  if (images.length === 0 && videos.length === 0) return null;

  return { images, videos };
}

/**
 * Swap in each object's web-sized copy after a live listing. A live listing
 * has no idea which derivatives exist, so the snapshot supplies that mapping;
 * anything without an entry keeps its full-resolution URL.
 */
function applyDerivatives(listed: MediaManifest): MediaManifest {
  const base = r2PublicBase;
  if (!base) return listed;

  const swap = (item: VenueMediaItem): VenueMediaItem => {
    const web = derivativeFor(item._id);
    return web
      ? {
          ...item,
          url: buildPublicUrl(base, web.key),
          size: web.size,
          // Matches `snapshotManifest`: the served copy's container is the
          // truth, not the original's.
          contentType: contentTypeFor(web.key),
        }
      : item;
  };

  return { images: listed.images.map(swap), videos: listed.videos.map(swap) };
}

function fallback(): MediaResolution {
  const snapshot = snapshotManifest();
  return snapshot
    ? { manifest: snapshot, source: "snapshot", stale: false }
    : { manifest: LOCAL_MEDIA, source: "local", stale: false };
}

/**
 * Resolve the media manifest. Never throws and never returns an empty list:
 * every failure path lands on a cached or bundled copy.
 */
export async function resolveMediaManifest(
  options: { fresh?: boolean } = {},
): Promise<MediaResolution> {
  const now = Date.now();

  if (!options.fresh && cache && now - cache.at < SUCCESS_TTL_MS) {
    return { manifest: cache.manifest, source: "cache", stale: false };
  }

  if (!hasLiveSource) return fallback();

  // Recently failed: don't touch the network again yet. Without this, every
  // page load pays the full listing timeout and an outage becomes a stampede.
  if (!options.fresh && failure && now - failure.at < FAILURE_TTL_MS) {
    const detail = `${failure.message} — not retried, a listing failed ${Math.round(
      (now - failure.at) / 1000,
    )}s ago`;
    return cache
      ? { manifest: cache.manifest, source: "cache", stale: true, error: detail }
      : { ...fallback(), stale: true, error: detail };
  }

  // Collapse concurrent callers onto one listing.
  inFlight ??= listLive();
  try {
    const listed = applyDerivatives(await inFlight);
    cache = { manifest: listed, at: Date.now() };
    failure = null;
    return { manifest: listed, source: "live", stale: false };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    failure = { at: Date.now(), message };
    return cache
      ? { manifest: cache.manifest, source: "cache", stale: true, error: message }
      : { ...fallback(), stale: true, error: message };
  } finally {
    inFlight = null;
  }
}
